indicators:
  - key: "total_tasks_completed_last_30_days"
    description: "total_tasks_completed_last_30_days_label"
    indicatorQuery: ""

  - key: "total_preg_last_30_days"
    description: "total_preg_last_30_days_label"
    indicatorQuery: ""