# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Print Java version
        run: java -version
      - name: Add Tasking for build
        run: cd .. && git clone https://github.com/OpenSRP/opensrp-client-tasking.git && cd opensrp-client-tasking && git checkout integrate-goldsmith && cd ../opensrp-client-goldsmith
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build project
        run: ./gradlew opensrp-app:build --stacktrace
      - name: Build APK (Maintain stability)
        run: ./gradlew opensrp-app:assembleDebug --stacktrace
